# Define environment
env=qa

# QA Environment
qa.baseUrl=https://www.amazon.in
qa.searchItem=HP smart tank
qa.productName=Smart Tank 589
qa.quantity=2

# UAT Environment
uat.baseUrl=https://www.amazon.in
uat.searchItem=HP smart tank
uat.productName=Smart Tank 589
uat.quantity=2

# PROD Environment
prod.baseUrl=https://www.amazon.in
prod.searchItem=HP smart tank
prod.productName=Smart Tank 589
prod.quantity=2